### PR TITLE
POW: use WebGL2 Curl.lib.js

### PR DESCRIPTION
**Pull request by paulhandy**

### CODE REVIEW

**Comment by cychotic** [comment]
I was trying to run a full node using PR234 and it kept giving the below error after maybe an hour.  I deleted all the .config/* files and retry.  Hour later, same thing.  I used the release version of 2.4.0, no problem yet.  I am not sure what it is about the PR234.  However, I did notice PoW worked a little better on my linux machine.

`08/27 15:04:42.870 [Solid Milestone Tracker] ERROR com.iota.iri.Milestone - Error during Solid Milestone updating
org.rocksdb.RocksDBException: block checksum mismatch
   at org.rocksdb.RocksDB.put(Native Method) ~[iri.jar:na]
   at org.rocksdb.RocksDB.put(RocksDB.java:472) ~[iri.jar:na]
   at com.iota.iri.storage.rocksDB.RocksDBPersistenceProvider.update(RocksDBPersistenceProvider.java:374) ~[iri.jar:na]
   at com.iota.iri.storage.Tangle.update(Tangle.java:92) ~[iri.jar:na]
   at com.iota.iri.controllers.TransactionViewModel.update(TransactionViewModel.java:139) ~[iri.jar:na]
   at com.iota.iri.controllers.TransactionViewModel.setValidity(TransactionViewModel.java:291) ~[iri.jar:na]
   at com.iota.iri.BundleValidator.validate(BundleValidator.java:95) ~[iri.jar:na]
   at com.iota.iri.LedgerValidator.getLatestDiff(LedgerValidator.java:92) ~[iri.jar:na]
   at com.iota.iri.LedgerValidator.updateSnapshot(LedgerValidator.java:269) ~[iri.jar:na]
   at com.iota.iri.Milestone.updateLatestSolidSubtangleMilestone(Milestone.java:199) ~[iri.jar:na]
   at com.iota.iri.Milestone.lambda$init$4(Milestone.java:126) ~[iri.jar:na]
   at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_144]`

**Comment by paulhandy** [comment]
@cychotic that appears to be an issue with you using it in full node mode.

**Comment by rajivshah3** [comment]
Small issue: sometimes, when I click the Reattach button, it doesn't show "reattaching...", and the only way the user would know that it actually is reattaching would be if they noticed the CPU spike or have the web inspector open. This could mislead the user into clicking reattach more than once

**Comment by alon-e** [comment]
failed while trying to transition:
```Uncaught ReferenceError: localAttachToTangle is not defined
    at ui.transition.js:214```
an additional override of `localAttachToTangle` is needed in transition (like in `lightwallet.js`).
https://github.com/iotaledger/wallet/blob/master/ui/js/ui.transition.js#L214

**Comment by paulhandy** [comment]
Thanks

**Comment by rajivshah3** [comment]
I also see that error when changing nodes, not sure if it’s related at all.

**Pull request merged**
